# Generated by Django 4.0.5 on 2022-06-15 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0002_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='topic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='searcher.topic'),
        ),
    ]
